import { CTAButton } from "@/components/CTAButton";
import { FinalCTA } from "@/components/FinalCTA";
import { HeroStage } from "@/components/HeroStage";
import { ImagePanel } from "@/components/ImagePanel";
import { Reveal } from "@/components/Reveal";
import { SectionHeader } from "@/components/SectionHeader";
import { heroImages, site } from "@/lib/site-data";
import { createMetadata } from "@/lib/seo";

export const metadata = createMetadata({ title: "About Adion Solar | From Film Production Power to Georgia Solar", description: "Learn how Adion’s film-production power roots shaped its practical approach to permanent residential, commercial, and project solar.", path: "/about" });

export default function AboutPage(){return <>
  <HeroStage eyebrow="About Adion" title="We learned solar where power has to work." copy="Adion Solar is a Madison, Georgia solar and energy company with roots in film and television production — an environment that rewards dependable equipment, practical engineering, and systems built around demanding operating conditions." image={heroImages.about} primaryHref="/contact" primaryLabel="Contact Adion" />
  <section className="px-5 py-16 sm:px-6 md:px-10 md:py-20 lg:py-24"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1.05fr_0.95fr] lg:gap-14"><Reveal><ImagePanel image={heroImages.commercial} tall label="North American field experience" /></Reveal><Reveal delay={.08}><SectionHeader eyebrow="Origin story" title="Our roots are mobile." copy="Before Adion was designing permanent systems for homes and businesses, solar-powered production trailers were operating across North America. More than 560 of those trailers are part of the operating experience behind Adion today. Film production was an unusually demanding classroom: loads change, equipment travels, schedules are unforgiving, and downtime matters." /><p className="body-copy mt-6 text-[#665a69]">That experience shaped a simple bias: understand what the system has to do, choose equipment that works together, and design around the way power will actually be used.</p></Reveal></div></section>
  <section className="bg-[#fffdf8] px-5 py-16 sm:px-6 md:px-10 md:py-20 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2 lg:gap-16"><Reveal><SectionHeader compact eyebrow="B.I. heritage" title="A B.I. Company" copy="Adion carries forward B.I.’s practical equipment and operating heritage. That matters because solar is not only a financial product; it is physical equipment that has to integrate with a property and continue working after the sale." /></Reveal><Reveal delay={.08}><SectionHeader compact eyebrow="Today" title="Today, the work is permanent too." copy="From its Madison base, Adion now works across residential, commercial, hospitality, manufacturing, and equipment applications. The setting changes. The expectation does not: the system has to make sense on paper and work in the field." /></Reveal></div></section>
  <section className="px-5 py-16 sm:px-6 md:px-10 md:py-20 lg:py-24"><div className="mx-auto max-w-7xl"><Reveal><SectionHeader eyebrow="Operating principles" title="Practical decisions, documented proof, and local accountability." /></Reveal><div className="mt-10 grid divide-y divide-[#482366]/14 border-y border-[#482366]/14 md:grid-cols-2 md:divide-x md:divide-y-0 lg:grid-cols-4">{[["Practical over generic","The recommendation should fit the job, not a preset package."],["Equipment matters","Panels, batteries, inverters, compatibility, and support belong in the same conversation."],["Proof over hype","Use documented projects and substantiated numbers when they exist."],["Local accountability","A Madison-based team, permanent location, and people customers can reach after the proposal."]].map(([title,copy])=><article key={title} className="py-7 md:px-6"><h2 className="font-serif text-3xl font-semibold text-[#241034]">{title}</h2><p className="mt-4 leading-7 text-[#665a69]">{copy}</p></article>)}</div></div></section>
  <section className="bg-[#241034] px-5 py-16 text-white sm:px-6 md:px-10 md:py-20 lg:py-24"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><Reveal><SectionHeader light eyebrow="Local close" title="Based in Madison. Built to work beyond it." /><div className="mt-8 grid gap-2 text-lg text-white/72"><a href={site.phoneHref}>{site.phone}</a><a href={`mailto:${site.email}`}>{site.email}</a><span>{site.address}</span></div></Reveal><CTAButton href="/contact">Contact Adion</CTAButton></div></section>
  <FinalCTA title="Tell us what you’re working on." copy="Start with the property, equipment, or support question and Adion will route the right next step." href="/contact" label="Contact Adion" />
  </>}
