import { CaseStudyFeature } from "@/components/CaseStudyFeature";
import { CTAButton } from "@/components/CTAButton";
import { FAQAccordion } from "@/components/FAQAccordion";
import { FinalCTA } from "@/components/FinalCTA";
import { HeroStage } from "@/components/HeroStage";
import { ImagePanel } from "@/components/ImagePanel";
import { Reveal } from "@/components/Reveal";
import { SectionHeader } from "@/components/SectionHeader";
import { caseStudies, commercialFaqs, heroImages } from "@/lib/site-data";
import { createMetadata } from "@/lib/seo";

export const metadata = createMetadata({ title: "Commercial Solar & Battery Systems in Georgia", description: "Commercial solar and storage evaluated around utility usage, facility operations, resilience needs, and project economics.", path: "/commercial-solar" });

const evaluationItems = ["Utility usage and rate structure", "Roof or land availability", "Electrical infrastructure", "Critical loads and battery goals", "Operating schedule and installation constraints", "System and equipment options", "Financing or incentive considerations, where applicable", "Projected production and project economics", "Monitoring, warranty, and support expectations"];

export default function CommercialSolarPage() {
  return <>
    <HeroStage eyebrow="Commercial Solar" title="Put your property to work lowering energy costs." copy="Adion evaluates commercial solar and battery systems around the economics and operating realities of your facility — so you can see whether the project makes financial sense before committing to it." image={heroImages.commercial} primaryHref="/contact?type=business" primaryLabel="Request Commercial Analysis" secondaryHref="/projects" secondaryLabel="View Projects" />
    <section className="site-section px-5 sm:px-6 md:px-10"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[0.9fr_1.1fr]"><Reveal><SectionHeader eyebrow="Business case" title="The proposal should start with the business case." copy="A commercial solar project is a capital decision, not simply a roof calculation. The analysis should account for utility usage, rate structure, available roof or land, operating schedule, storage needs, installation constraints, and the financial questions that determine whether the project deserves to move forward." /><div className="mt-8 flex flex-wrap gap-3">{["Lower purchased energy", "Model project economics", "Evaluate storage + resilience", "Plan around operations"].map(item => <span key={item} className="rounded-full bg-[#482366]/8 px-4 py-3 text-xs font-black uppercase tracking-[0.15em] text-[#482366]">{item}</span>)}</div></Reveal><Reveal delay={0.08}><ImagePanel image={heroImages.commercial} tall label="Facility-scale planning" /></Reveal></div></section>
    <section className="site-section bg-[#fffdf8] px-5 sm:px-6 md:px-10"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.75fr_1.25fr]"><Reveal><SectionHeader eyebrow="Site evaluation" title="What we evaluate before recommending a system." /></Reveal><div className="grid gap-x-8 border-y border-[#482366]/14 sm:grid-cols-2">{evaluationItems.map((item,index)=><Reveal key={item} delay={index*0.03}><p className="border-b border-[#482366]/12 py-5 font-semibold text-[#241034]">{String(index+1).padStart(2,"0")} <span className="ml-4">{item}</span></p></Reveal>)}</div></div></section>
    <section className="site-section px-5 sm:px-6 md:px-10"><div className="mx-auto max-w-7xl"><Reveal><SectionHeader eyebrow="Applications" title="Built for more than one kind of business." copy="Manufacturing, hospitality, warehouses, offices, industrial properties, campuses, and local businesses all begin with the same question: does the project fit the property and the economics?" /></Reveal><div className="mt-10 flex flex-wrap gap-3">{["Manufacturing","Hospitality","Warehouses","Offices","Industrial properties","Campuses","Local businesses"].map(item=><span key={item} className="rounded-full bg-[#241034] px-5 py-3 text-sm font-bold text-white">{item}</span>)}</div><div className="mt-8"><CTAButton href="/projects" variant="dark">Explore Projects</CTAButton></div></div></section>
    <section className="site-section bg-[#fffdf8] px-5 sm:px-6 md:px-10"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.8fr_1.2fr]"><Reveal><SectionHeader eyebrow="Madison, Georgia" title="B.I. Production Works — Madison, Georgia" copy="The current published project model shows a 73.4% solar offset and $413,945 in projected 25-year savings — a concrete example of putting site and utility data behind the decision." /><div className="mt-8"><CTAButton href="/case-studies/bi-production-works" variant="dark">View Project</CTAButton></div></Reveal><Reveal delay={0.08}><CaseStudyFeature caseStudy={caseStudies[0]} /></Reveal></div></section>
    <section className="site-section px-5 sm:px-6 md:px-10"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.8fr_1.2fr]"><Reveal><SectionHeader eyebrow="Commercial FAQ" title="Questions that shape the business case." /></Reveal><FAQAccordion faqs={commercialFaqs} /></div></section>
    <FinalCTA title="Put project-specific numbers around the opportunity." copy="Send the property and utility context. We’ll help you determine whether the project deserves a closer look." href="/contact?type=business" label="Request Commercial Analysis" />
  </>;
}
